### ISSUE TITLE
Dropdown closing issue in settings modal.

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/Apps.Whiteboard#55] opened 2023-12-27 08:20 UTC
### BRIEF TITLE:
The dropdown selection is not getting closed after selecting an option from the **Update Board Privacy** dropdown. It is also not getting closed when clicking somewhere outside on the modal.

### SCREENSHOTS/SCREENRECORD:

[dropdown.webm](https://github.com/RocketChat/Apps.Whiteboard/assets/95426993/01534ed8-5d98-4a3f-ac85-6caccd3b4620)

**Comment by CulturalProfessor** [comment] 2023-12-27 15:43
[Screencast from 27-12-23 09:12:24 PM IST.webm](https://github.com/RocketChat/Apps.Whiteboard/assets/92238941/abdfed31-2c35-4ebf-9e56-d8e02249173e)

I think for me it's working fine

**Comment by CulturalProfessor** [comment] 2023-12-30 11:06
> Screencast.from.27-12-23.09.12.24.PM.IST.webm 
> I think for me it's working fine

if @Sumitwarrior7 @brf153 also confirm it's working as intended we can close this issue

**Comment by brf153** [comment] 2023-12-30 11:08
Its working in my system. I am not getting this error.

**Closed** 2023-12-30 11:20 UTC
